# docker-compose.yml
version: '3.0'
services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    # build: .
    image: ch0k89/chat2:latest
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db